---
title: "gathering-data"
author: "Alexander Park"
date: "10/15/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(janitor)
library(rstanarm)
require("knitr")

# I have commented out the following line so as not to crash anyone else's
# computer. This line was for me to set my working directory.

# opts_knit$set(root.dir = "~/Desktop/GOV_50/home-field-advantage/shiny-app")
```

# NFL Average Score Data

```{r nfl}

# Create object nfl_scores_1966 that has all scores from NFL games from 1966-67
# to 2019-2020 (pre-COVID). I clean this up by assigning data for defunct teams
# to teams that succeeded them.

nfl_scores_1966 <- read_csv("raw_data/nflscores1966/spreadspoke_scores.csv",
                            col_types = cols(schedule_date = col_character(),
                                             schedule_season = col_double(),
                                             schedule_week = col_character(),
                                             schedule_playoff = col_logical(),
                                             team_home = col_character(),
                                             score_home = col_double(),
                                             score_away = col_double(),
                                             team_away = col_character(),
                                             team_favorite_id = col_character(),
                                             spread_favorite = col_double(),
                                             over_under_line = col_double(),
                                             stadium = col_character(),
                                             stadium_neutral = col_logical(),
                                             weather_temperature = col_double(),
                                             weather_wind_mph = col_double(),
                                             weather_humidity = col_character(),
                                             weather_detail = 
                                               col_character())) %>%
  mutate(team_home = case_when(team_home == "Baltimore Colts" ~ 
                                 "Indianapolis Colts",
                               team_home == "Boston Patriots" ~
                                 "New England Patriots",
                               team_home == "Houston Oilers" ~
                                 "Tennessee Titans",
                               team_home == "Phoenix Cardinals" ~
                                 "Arizona Cardinals",
                               team_home == "Los Angeles Raiders" ~ 
                                 "Las Vegas Raiders",
                               team_home == "Oakland Raiders" ~
                                 "Las Vegas Raiders",
                               team_home == "Tennessee Oilers" ~
                                 "Tennessee Titans",
                               team_home == "Washington Redskins" ~
                                 "Washington Football Team",
                               team_home == "San Diego Chargers" ~
                                 "Los Angeles Chargers",
                               team_home == "St. Louis Cardinals" ~
                                 "Arizona Cardinals",
                               team_home == "St. Louis Rams" ~
                                 "Los Angeles Rams",
                               TRUE ~ team_home)) %>%
  mutate(team_away = case_when(team_away == "Baltimore Colts" ~ 
                                 "Indianapolis Colts",
                               team_away == "Boston Patriots" ~
                                 "New England Patriots",
                               team_away == "Houston Oilers" ~
                                 "Tennessee Titans",
                               team_away == "Phoenix Cardinals" ~
                                 "Arizona Cardinals",
                               team_away == "Los Angeles Raiders" ~ 
                                 "Las Vegas Raiders",
                               team_away == "Oakland Raiders" ~
                                 "Las Vegas Raiders",
                               team_away == "Tennessee Oilers" ~
                                 "Tennessee Titans",
                               team_away == "Washington Redskins" ~
                                 "Washington Football Team",
                               team_away == "San Diego Chargers" ~
                                 "Los Angeles Chargers",
                               team_away == "St. Louis Cardinals" ~
                                 "Arizona Cardinals",
                               team_away == "St. Louis Rams" ~
                                 "Los Angeles Rams",
                               TRUE ~ team_away))

# Create object avg_nfl_home_score that is the average score that home teams
# have had over the years. Specify that teams are at home.

avg_nfl_home_score <- nfl_scores_1966 %>%
  group_by(team_home) %>%
  summarize(avg_home = mean(score_home), .groups = "drop") %>%
  rename(team = team_home,
         score = avg_home) %>%
  mutate(condition = "Home")

# Create object avg_nfl_away_score that is the average score that away teams
# have had over the years. Specify that teams are away.

avg_nfl_away_score <- nfl_scores_1966 %>%
  group_by(team_away) %>%
  summarize(avg_away = mean(score_away), .groups = "drop") %>%
  rename(team = team_away,
         score = avg_away) %>%
  mutate(condition = "Away")

# Combine avg_nfl_home_score with avg_nfl_away_score to create avg_nfl_score.
# Specify that the teams and scores are from the NFL for future combining
# purposes.

avg_nfl_score <- bind_rows(avg_nfl_home_score, 
                            avg_nfl_away_score) %>%
  mutate(league = "NFL")

```

# NBA Average Score Data

```{r nba}

# Create object nba_names_2004 to organize NBA team names.

nba_names_2004 <- read_csv("raw_data/nba2004/teams.csv", 
                           col_types = cols(LEAGUE_ID = col_character(),
                                            TEAM_ID = col_double(),
                                            MIN_YEAR = col_double(),
                                            MAX_YEAR = col_double(),
                                            ABBREVIATION = col_character(),
                                            NICKNAME = col_character(),
                                            YEARFOUNDED = col_double(),
                                            CITY = col_character(),
                                            ARENA = col_character(),
                                            ARENACAPACITY = col_double(),
                                            OWNER = col_character(),
                                            GENERALMANAGER = col_character(),
                                            HEADCOACH = col_character(),
                                            DLEAGUEAFFILIATION = 
                                              col_character())) %>%
  clean_names()

# Combine values from the city and nickname columns to create a name column with
# the conventional NBA team names.

nba_names_2004 <- nba_names_2004 %>%
  select(city, nickname, team_id) %>%
  unite(name, c("city", "nickname"), sep = " ")

# Create object nba_scores_2004 that has all scores from NBA games from 2004
# to March 2020.

nba_scores_2004 <- read_csv("raw_data/nba2004/games.csv",
                            col_types = cols(.default = col_double(),
                                             GAME_DATE_EST = 
                                               col_date(format = ""),
                                             GAME_STATUS_TEXT = 
                                               col_character())) %>%
  clean_names() %>%
  rename(team_id = home_team_id) %>%
  select(team_id, visitor_team_id, season, pts_home, pts_away)

# Manipulate nba_scores_2004 and nba_names_2004 so that nba_scores_2004 displays
# scores and conventional NBA team names for home and away teams.

nba_scores_2004 <- left_join(nba_scores_2004, 
                             nba_names_2004, 
                             by = "team_id") %>%
  rename(home_team = name)

nba_names_2004_away <- nba_names_2004 %>%
  rename(visitor_team_id = team_id)
  
nba_scores_2004 <- left_join(nba_scores_2004, 
                             nba_names_2004_away, 
                             by = "visitor_team_id") %>%
  rename(away_team = name) %>%
  select(home_team, away_team, season, pts_home, pts_away)

# Create object avg_nba_home_score that is the average score that home teams
# have had over the years. Specify that these are home average scores.

avg_nba_home_score <- nba_scores_2004 %>%
  select(home_team, pts_home) %>%
  group_by(home_team) %>%
  summarize(avg_home = mean(pts_home, na.rm = TRUE), .groups = "drop") %>%
  rename(team = home_team,
         score = avg_home) %>%
  mutate(condition = "Home")

# Create object avg_nba_away_score that is the average score that away teams
# have had over the years. Specify that these are away average scores.

avg_nba_away_score <- nba_scores_2004 %>%
  select(away_team, pts_away) %>%
  group_by(away_team) %>%
  summarize(avg_away = mean(pts_away, na.rm = TRUE), .groups = "drop") %>%
  rename(team = away_team,
         score = avg_away) %>%
  mutate(condition = "Away")

# Combine avg_nba_home_score with avg_nba_away_score into avg_nba_score. Specify
# that these teams and scores are from the NBA for future combining purposes.

avg_nba_score <- bind_rows(avg_nba_home_score, 
                            avg_nba_away_score) %>%
  mutate(league = "NBA")

```

# MLB Average Score Data

```{r mlb}

# Create object mlb_scores_1947 that has all scores from MLB games from 1947
# (when the MLB became racially integrated) to October 2019 (pre-Covid). I clean
# the data to display team names instead of team IDs.
  
mlb_scores_1947 <- read_csv("raw_data/mlbscores/mlb_elo.csv", 
                            col_types = cols(.default = col_double(),
                                             date = col_date(format = ""),
                                             playoff = col_character(),
                                             team1 = col_character(),
                                             team2 = col_character(),
                                             pitcher1 = col_character(),
                                             pitcher2 = col_character())) %>%
  clean_names() %>%
  rename(home_team_id = team1,
         away_team_id = team2,
         home_score = score1,
         away_score = score2) %>%
  filter(season >= 1947) %>%
  filter(season != 2020) %>%
  mutate(home_team_id = case_when(home_team_id == "ANA" ~ "LAA",
                                  TRUE ~ home_team_id)) %>%
  mutate(away_team_id = case_when(away_team_id == "ANA" ~ "LAA",
                                  TRUE ~ away_team_id)) %>%
  mutate(home_team = case_when(home_team_id == "HOU" ~ "Houston Astros",
                               home_team_id == "WSN" ~ "Washington Nationals",
                               home_team_id == "NYY" ~ "New York Yankees",
                               home_team_id == "STL" ~ "St. Louis Cardinals",
                               home_team_id == "LAD" ~ "Los Angeles Dodgers",
                               home_team_id == "ATL" ~ "Atlanta Braves",
                               home_team_id == "TBD" ~ "Tampa Bay Rays",
                               home_team_id == "MIN" ~ "Minnesota Twins",
                               home_team_id == "OAK" ~ "Oakland Athletics",
                               home_team_id == "KCR" ~ "Kansas City Royals",
                               home_team_id == "SEA" ~ "Seattle Mariners",
                               home_team_id == "NYM" ~ "New York Mets",
                               home_team_id == "COL" ~ "Colorado Rockies",
                               home_team_id == "CHW" ~ "Chicago White Sox",
                               home_team_id == "ARI" ~ "Arizona Diamondbacks",
                               home_team_id == "TOR" ~ "Toronot Blue Jays",
                               home_team_id == "LAA" ~ "Los Angeles Angels",
                               home_team_id == "TEX" ~ "Texas Rangers",
                               home_team_id == "SFG" ~ "San Francisco Giants",
                               home_team_id == "PIT" ~ "Pittsburgh Pirates",
                               home_team_id == "PHI" ~ "Philadelphia Phillies",
                               home_team_id == "BOS" ~ "Boston Red Sox",
                               home_team_id == "SDP" ~ "San Diego Padres",
                               home_team_id == "DET" ~ "Detroit Tigers",
                               home_team_id == "CIN" ~ "Cincinnati Reds",
                               home_team_id == "CLE" ~ "Cleveland Indians",
                               home_team_id == "CHC" ~ "Chicago Cubs",
                               home_team_id == "MIL" ~ "Milwaukee Brewers",
                               home_team_id == "FLA" ~ "Miami Marlins",
                               home_team_id == "BAL" ~ "Baltimore Orioles",
                               TRUE ~ home_team_id)) %>%
  mutate(away_team = case_when(away_team_id == "HOU" ~ "Houston Astros",
                               away_team_id == "WSN" ~ "Washington Nationals",
                               away_team_id == "NYY" ~ "New York Yankees",
                               away_team_id == "STL" ~ "St. Louis Cardinals",
                               away_team_id == "LAD" ~ "Los Angeles Dodgers",
                               away_team_id == "ATL" ~ "Atlanta Braves",
                               away_team_id == "TBD" ~ "Tampa Bay Rays",
                               away_team_id == "MIN" ~ "Minnesota Twins",
                               away_team_id == "OAK" ~ "Oakland Athletics",
                               away_team_id == "KCR" ~ "Kansas City Royals",
                               away_team_id == "SEA" ~ "Seattle Mariners",
                               away_team_id == "NYM" ~ "New York Mets",
                               away_team_id == "COL" ~ "Colorado Rockies",
                               away_team_id == "CHW" ~ "Chicago White Sox",
                               away_team_id == "ARI" ~ "Arizona Diamondbacks",
                               away_team_id == "TOR" ~ "Toronot Blue Jays",
                               away_team_id == "LAA" ~ "Los Angeles Angels",
                               away_team_id == "TEX" ~ "Texas Rangers",
                               away_team_id == "SFG" ~ "San Francisco Giants",
                               away_team_id == "PIT" ~ "Pittsburgh Pirates",
                               away_team_id == "PHI" ~ "Philadelphia Phillies",
                               away_team_id == "BOS" ~ "Boston Red Sox",
                               away_team_id == "SDP" ~ "San Diego Padres",
                               away_team_id == "DET" ~ "Detroit Tigers",
                               away_team_id == "CIN" ~ "Cincinnati Reds",
                               away_team_id == "CLE" ~ "Cleveland Indians",
                               away_team_id == "CHC" ~ "Chicago Cubs",
                               away_team_id == "MIL" ~ "Milwaukee Brewers",
                               away_team_id == "FLA" ~ "Miami Marlins",
                               away_team_id == "BAL" ~ "Baltimore Orioles",
                               TRUE ~ away_team_id))

# Create object avg_mlb_home_score that is the average score that home teams
# have had over the years. Specify that these are home average scores.

avg_mlb_home_score <- mlb_scores_1947 %>%
  select(home_team, home_score) %>%
  group_by(home_team) %>%
  summarize(avg_home = mean(home_score, na.rm = TRUE), .groups = "drop") %>%
  rename(team = home_team,
         score = avg_home) %>%
  mutate(condition = "Home")

# Create object avg_mlb_away_score that is the average score that away teams
# have had over the years. Specify that these are away average scores.

avg_mlb_away_score <- mlb_scores_1947 %>%
  select(away_team, away_score) %>%
  group_by(away_team) %>%
  summarize(avg_away = mean(away_score, na.rm = TRUE), .groups = "drop") %>%
  rename(team = away_team,
         score = avg_away) %>%
  mutate(condition = "Away")

# Combine avg_mlb_home_score with avg_mlb_away_score. Specify that these teams
# and scores are from the MLB for future combining purposes.

avg_mlb_score <- bind_rows(avg_mlb_home_score, 
                            avg_mlb_away_score) %>%
  mutate(league = "MLB")

```

# Combining NFL, NBA, and MLB Data

```{r combining}

# Here, I am combining the NFL, NBA, and MLB average score tibbles for the
# purposes of the "AvgScoreInteractive" graph on the Introduction tab of my
# project.

combined_league_data <- bind_rows(avg_nfl_score,
                                  avg_nba_score,
                                  avg_mlb_score)

# Saving RDS.

saveRDS(combined_league_data, file = "combined_league_data.RDS")

```


# NFL Model

$$ score = \beta_0 + \beta_1 home_i + \epsilon_i $$

```{r nfl model}

# Here, I am wrangling NFL data to create nfl_model_data for use in my nfl_model
# below, but also for the "NFLModelInteractive" graph in my NFL tab.

# For home data, I specify home = 1.

nfl_model_data_home <- nfl_scores_1966 %>%
  select(team_home, score_home, schedule_season) %>%
  mutate(home = 1) %>%
  rename(team = team_home,
         score = score_home,
         season = schedule_season)

# For away data, I specify home = 0.

nfl_model_data_away <- nfl_scores_1966 %>%
  select(team_away, score_away, schedule_season) %>%
  mutate(home = 0) %>%
  rename(team = team_away,
         score = score_away,
         season = schedule_season)

# Combine both home and away halves to create one tibble.

nfl_model_data <- bind_rows(nfl_model_data_home, nfl_model_data_away)
  
# Save RDS.

saveRDS(nfl_model_data, file = "nfl_model_data.RDS")

# Here, I make the NFL model using stan_glm() in order to predict the difference
# in scores between home and away games for the league, on the whole.

nfl_model <- stan_glm(score ~ home,
                      data = nfl_model_data,
                      refresh = 0)

print(nfl_model, digits = 4)

# Save RDS.

saveRDS(nfl_model, file = "nfl_model.RDS")

```

# MLB Model

$$ score = \beta_0 + \beta_1 home_i + \beta_2 attendance_i + \beta_3 home_i * attendance_i + \epsilon_i $$

```{r mlb model}

# Here, I gather MLB attendance data. I filter by season to match the season
# parameters of my MLB scores data. I make the column avg_attendance for my
# model later on.

mlb_attendance_raw <- read_csv("raw_data/mlbscores/Teams.csv", 
                               col_types = cols(teamID = col_character())) %>%
  filter(yearID >= 1947) %>%
  filter(yearID != 2020) %>%
  select(yearID, Ghome, attendance, teamID, name) %>%
  mutate(avg_attendance = attendance / Ghome)

# Here, I further clean the mlb_scores dataset

mlb_scores_raw <- mlb_scores_1947 %>%
  select(date, 
         season, 
         home_team_id, 
         away_team_id,
         home_team,
         away_team,
         home_score, 
         away_score)

# Here, I edit mlb_attendance_raw to reflect the modern names of teams. I also
# create marker columns in mlb_attendance and mlb_scores for easy combining
# later on.

mlb_attendance <- mlb_attendance_raw %>%
  mutate(team = case_when(teamID == "BRO" ~ "LAD",
                          teamID == "BSN" ~ "ATL",
                          teamID == "CHA" ~ "CHW",
                          teamID == "NY1" ~ "SFG",
                          teamID == "NYA" ~ "NYY",
                          teamID == "PHA" ~ "OAK",
                          teamID == "SLA" ~ "BAL",
                          teamID == "WS1" ~ "MIN",
                          teamID == "ML1" ~ "ATL",
                          teamID == "KS1" ~ "OAK",
                          teamID == "LAN" ~ "LAD",
                          teamID == "WS2" ~ "TEX",
                          teamID == "NYN" ~ "NYM",
                          teamID == "CAL" ~ "LAA",
                          teamID == "KCA" ~ "KCR",
                          teamID == "MON" ~ "WSN",
                          teamID == "SDN" ~ "SDP",
                          teamID == "SE1" ~ "MIL",
                          teamID == "ML4" ~ "MIL",
                          teamID == "FLO" ~ "FLA",
                          teamID == "TBA" ~ "TBD",
                          teamID == "WAS" ~ "WSN",
                          teamID == "MIA" ~ "FLA",
                          TRUE ~ teamID)) %>%
  select(yearID, team, attendance, avg_attendance) %>%
  mutate(marker = str_c(yearID, team, sep = " "))

mlb_scores <- mlb_scores_raw %>%
  mutate(marker = str_c(season, home_team_id, sep = " "))

# Here, I combine both mlb_scores and mlb_attendance.

mlb_combined <- left_join(mlb_scores, mlb_attendance, by = "marker") %>%
  select(season,
         home_team,
         away_team,
         home_score,
         away_score,
         avg_attendance)

# I mutate the "avg_attendance" column (divide it by 1000) to make the
# "attendance" column so that my analysis can be the change in score depending
# on every 1000 fans are in attendance.

# For home data, I specify home = 1.

mlb_model_data_home <- mlb_combined %>%
  select(home_team, home_score, avg_attendance, season) %>%
  mutate(home = 1) %>%
  mutate(attendance = avg_attendance / 1000) %>%
  rename(team = home_team,
         score = home_score)

# For away data, I specify home = 0.

mlb_model_data_away <- mlb_combined %>%
  select(away_team, away_score, avg_attendance, season) %>%
  mutate(home = 0) %>%
  mutate(attendance = avg_attendance / 1000) %>%
  rename(team = away_team,
         score = away_score)

# Combine both home and away halves to create mlb_model_data. This will be used
# in the MLB model I make later on, as well as in making the
# "MLBModelInteractive" visualization in the MLB tab.

mlb_model_data <- bind_rows(mlb_model_data_home, mlb_model_data_away) %>%
  select(team, score, home, attendance, season)

# Save RDS for mlb_model_data.

saveRDS(mlb_model_data, file = "mlb_model_data.RDS")


# Here, I make the MLB model using stan_glm() in order to predict the difference
# in scores between home and away games for the league, on the whole.

mlb_model_complex <- stan_glm(score ~ home + attendance + home * attendance,
                      data = mlb_model_data,
                      refresh = 0)

print(mlb_model_complex, digits = 4)

# Save RDS.

saveRDS(mlb_model_complex, file = "mlb_model_complex.RDS")

```

# NBA Model

$$ score = \beta_0 + \beta_1 home_i + \epsilon_i $$

```{r nba model}

# Here, I wrangle NBA data for the NBA model.

# For home data, I specify home = 1.

nba_model_data_home <- nba_scores_2004 %>%
  select(home_team, 
         pts_home,
         season) %>%
  mutate(home = 1) %>%
  rename(team = home_team,
         score = pts_home)

# For away data, I specify home = 0.

nba_model_data_away <- nba_scores_2004 %>%
  select(away_team, 
         pts_away,
         season) %>%
  mutate(home = 0) %>%
  rename(team = away_team,
         score = pts_away)

# Here, I make the tibble for the NBA model.This tibble will also be used in
# making the "NBAModelInteractive" graphic in my NBA tab.

nba_model_data <- bind_rows(nba_model_data_home, nba_model_data_away)

# Here, I make the NBA model using stan_glm() in order to predict the difference
# in scores between home and away games for the league, on the whole.

nba_model <- stan_glm(score ~ home,
                      data = nba_model_data,
                      refresh = 0)

print(nba_model, digits = 4)

# Save RDS of NBA model.

saveRDS(nba_model, file = "nba_model.RDS")

# Save RDS of nba_model_data for use with interactive graphic.

saveRDS(nba_model_data, file = "nba_model_data.RDS")

```
